### ISSUE TITLE
Problema legata de autograding.

### ISSUE THREAD

**Issue by githubNicolasN** [UPB-FILS-ALF/questions#1]
Am terminat tema si la final imi apare 100/100 dar am primit un email in care imi apare un workflow diferit in care autogradingul are 50/100.Workflow-ul defectuos din mail este #8,cel real pe care tema e corecta e #13.

**Comment by alexandruradovici** [comment]
Please ask the questions in English next time. 

Autograding will grade every commit, we will take into account the last commit that meets the homework deadline.
