### ISSUE TITLE
devoir 1 simulator

### ISSUE THREAD

**Issue by andrei-matea** [UPB-FILS-ALF/questions#10]
Buna seara, am o intrebare: cand citesc de ex. fisierul stack.asm mi se afiseaza "push 300, push 200, print" in loc de [ 300,200 ]. Cum pot modifica fisierul index.ts astfel incat sa apara rezultatul corect ( 300,200 ) ? Multumesc

**Comment by alexandruradovici** [comment]
You have to solve the homework, reading the file is just the first step.
