### ISSUE TITLE
devoir 1-simulateur cpu-undefined label

### ISSUE THREAD

**Issue by AndreiCristianMoga** [UPB-FILS-ALF/questions#12]
i did not understand the concept of an _"undefined label"_ for one of the errors, can someone please give me an explanation about 'defined' labels? how or where should i define them (if i should), in order to be able to have and find the undefined ones?

**Comment by alexandruradovici** [comment]
An undefined label is a label that appears in a jump instruction but has no corresponding line in the rest of the file.
