### ISSUE TITLE
Autochecker fails?

### ISSUE THREAD

**Issue by rockmenme** [UPB-FILS-ALF/questions#14]
Hello, so I wrote some code that, and I decided to test it. 
I've uploaded it on github, and the autochecker started doing it's magic, yet it doesn't register my output. I've been looking into it and I saw some tests, like "./devoir-1-tests/tests/stack_and_math/add.asm" witch has my output file empty. I decided to test it on my machine, with the test downloaded from github, and I do have an output that works.
Here is the output on my machine : https://gyazo.com/34e4efa17fe8607ac2589209b9704e7b
Here is the output on the checker : https://gyazo.com/f23fed265da00465b2b80fd5de7d6fcd

Any ideas of fixing this?

**Comment by ghost** [comment]
I have the same issue.
In my computer all is good but in github all is bad

**Comment by alexandruradovici** [comment]
Use /\r?\n/ to split lines, as suggested in the rules (https://ocw.cs.pub.ro/courses/alf/teme/tema_en_1#rules). Windows uses \r\n, while Linux only uses \n.

**Comment by ghost** [comment]
Still not working

**Comment by alexandruradovici** [comment]
> Still not working

Still not changed in your code :wink:

**Comment by ghost** [comment]
J'ai changé et c'est toujours pareil
