### ISSUE TITLE
About the readme file

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#15]
How much detail is enough for the readme file?

**Comment by alexandruradovici** [comment]
As much as you can

**Comment by HoszuAndreiAlexandru** [comment]
I understand, thank you :D!

**Comment by HoszuAndreiAlexandru** [comment]
But what about the language? Can we write it in romanian, or is english/french required?

**Comment by alexandruradovici** [comment]
> But what about the language? Can we write it in romanian, or is english/french required?

Romanian is fine

**Comment by HoszuAndreiAlexandru** [comment]
Ok thanks again :D
