### ISSUE TITLE
[Devoir 2 - Design language] Problem encountered while running the run.sh script 

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-ALF/questions#17]
When I try to run the run.sh script on VS Code I get the "run.sh: line 19: compare: command not found" error, no matter what test file is currently checked. Can there be a problem with my VS Code or the script itself? This is how the terminal looks when I run the run.sh script:

![2021-03-27 (2)](https://user-images.githubusercontent.com/63002082/112724416-e8f21400-8f1b-11eb-9b99-e21e11a84b36.png)

**Comment by alexandruradovici** [comment]
You have to install the convert utility:

```bash
$ sudo apt-get install imagemagick
```
