### ISSUE TITLE
Task : POSITION -> Erreurs -> POSITION has *2* parameters and not 3.

### ISSUE THREAD

**Issue by AbdelmadjidBOUR** [UPB-FILS-ALF/questions#18]
![image](https://user-images.githubusercontent.com/79580257/112756249-3f268c00-8fdc-11eb-8680-6eef589f3278.png)

**Comment by alexandruradovici** [comment]
Fixed, thank you

**Comment by AbdelmadjidBOUR** [comment]
You are welcome.
