### ISSUE TITLE
Devoir 2 Tests

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#19]
Is it correct for the test line_polar_variable.dsn to have the lenght and the angle before the polar parameter?[1]

Another question is about the location parameter in the line command because in the homework requirements it is as : "LINE: position a b" and in the tests it is as "LINE: p1 p2 location"[2]

[1]
![image](https://user-images.githubusercontent.com/19248295/112766342-086f6680-901a-11eb-8c22-d4248c9b132d.png)
[2]
![image](https://user-images.githubusercontent.com/19248295/112766377-33f25100-901a-11eb-80d1-e173bc7786eb.png)

**Comment by alexandruradovici** [comment]
You are right, we fixed the homework's text.

**Comment by SheepSeb** [comment]
I have another question because in the tests the error output should be "LINE 3 HAS ERROR: LINE parameter 3 needs to be one of (location, polar), you wrote line" , but in the homework req. the error is stated as "ERROR LINE (line_number): LINE parameter 1 requires one of (position, polar), you wrote (actual_written_parameter_value)"

**Comment by alexandruradovici** [comment]
Fixed
