### ISSUE TITLE
Homework 1 : My output seems to be correct but ./test.sh says it's not

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#2]
My output seems to be correct but the script says that it's wrong. Is there any special output format?
![image](https://user-images.githubusercontent.com/19248295/110493539-5f5cdc80-80fb-11eb-83f2-dbc3924366c5.png)

**Comment by alexandruradovici** [comment]
I have two issues in mind:
 - you have some white space at the end of the lines
 - the end of the line is not the same, tests have \n, if you are testing in windows, that might be a problem, as git might checkout files with \n\r

We modified the tests to ignore trailing white space, try again, but remove the tests folder first.
