### ISSUE TITLE
Devoir 2 Polar coords

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#20]
So I have tried with the following formulas to transform from polar coords to cartesian coord 

x = l * cos (a)
y = l * sin (a)
with a in deg

but in the tests it outputs a different result than what i've expected 
for the following [1]
[1]
![image](https://user-images.githubusercontent.com/19248295/112898835-0379e800-90ea-11eb-99f9-0cc3cd0ee623.png)

from the calculator i get these
[2]
![image](https://user-images.githubusercontent.com/19248295/112899326-b1859200-90ea-11eb-86f4-8d1bfabb5486.png)

But in the svg file the coords for the line are [3]
[3]
![image](https://user-images.githubusercontent.com/19248295/112899362-bb0efa00-90ea-11eb-9346-68b2388889ff.png)

**Comment by HoszuAndreiAlexandru** [comment]
I also noticed this; apparently they used y = a * sin (a) and not y = l * sin (a).

**Comment by alexandruradovici** [comment]
We pushed a fix to this, please try it now.
