### ISSUE TITLE
Devoir 2 Multiple issues

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#21]
For the loop variable test:
![image](https://user-images.githubusercontent.com/79837301/112958364-1244b700-914b-11eb-9df6-4a77a24162d9.png)

It looks like the COLOR command can receive negative values as parameters, as the svg file looks like this:
![image](https://user-images.githubusercontent.com/79837301/112958806-7d8e8900-914b-11eb-8e34-fcd8e11baa7d.png)
or
![image](https://user-images.githubusercontent.com/79837301/112958873-8c753b80-914b-11eb-9596-adf71f5c008d.png)

According to your documentation, shouldn't COLOR only receive parameters that have values between 0 and 255?

**Comment by HoszuAndreiAlexandru** [comment]
I also noticed that run.sh shows my output under "Correct output" and the .out files under "Your output".

**Comment by HoszuAndreiAlexandru** [comment]
Also, in the documentation it says that rectangle does not move the current position, but in your tests it does change.

**Comment by HoszuAndreiAlexandru** [comment]
Also, the errors are different:
In your documentation it says it should start like this: "ERROR LINE (line_number): ...".
In your tests they all look like this: "LINE line_number HAS ERROR: ...".

And this error for both WHILE and LOOP:
![image](https://user-images.githubusercontent.com/79837301/112970360-c992fb00-9156-11eb-8a5a-ae828b6b595b.png)

looks like is replaced by "LINE line_number HAS ERROR: LOOP with no REPEAT" in your .out files.

**Comment by alexandruradovici** [comment]
> I also noticed that run.sh shows my output under "Correct output" and the .out files under "Your output".

Fixed, please try it now. 

Next time open an issue for each different question.

**Comment by alexandruradovici** [comment]
> For the loop variable test:
> ![image](https://user-images.githubusercontent.com/79837301/112958364-1244b700-914b-11eb-9df6-4a77a24162d9.png)
> 
> It looks like the COLOR command can receive negative values as parameters, as the svg file looks like this:
> ![image](https://user-images.githubusercontent.com/79837301/112958806-7d8e8900-914b-11eb-8e34-fcd8e11baa7d.png)
> or
> ![image](https://user-images.githubusercontent.com/79837301/112958873-8c753b80-914b-11eb-9596-adf71f5c008d.png)
> 
> According to your documentation, shouldn't COLOR only receive parameters that have values between 0 and 255?

You are right, they should be greater than 0, but if they are like this due to math, just ignore use them anyway.

**Comment by alexandruradovici** [comment]
> Also, the errors are different:
> In your documentation it says it should start like this: "ERROR LINE (line_number): ...".
> In your tests they all look like this: "LINE line_number HAS ERROR: ...".
> 
We fixed it, please try it now.

> And this error for both WHILE and LOOP:
> ![image](https://user-images.githubusercontent.com/79837301/112970360-c992fb00-9156-11eb-8a5a-ae828b6b595b.png)
> 
> looks like is replaced by "LINE line_number HAS ERROR: LOOP with no REPEAT" in your .out files.


Use the way it is written in the tests.

**Comment by HoszuAndreiAlexandru** [comment]
> 
> 
> > I also noticed that run.sh shows my output under "Correct output" and the .out files under "Your output".
> 
> Fixed, please try it now.
> 
> Next time open an issue for each different question.

Understood

**Comment by HoszuAndreiAlexandru** [comment]
> 
> 
> > For the loop variable test:
> > ![image](https://user-images.githubusercontent.com/79837301/112958364-1244b700-914b-11eb-9df6-4a77a24162d9.png)
> > It looks like the COLOR command can receive negative values as parameters, as the svg file looks like this:
> > ![image](https://user-images.githubusercontent.com/79837301/112958806-7d8e8900-914b-11eb-8e34-fcd8e11baa7d.png)
> > or
> > ![image](https://user-images.githubusercontent.com/79837301/112958873-8c753b80-914b-11eb-9596-adf71f5c008d.png)
> > According to your documentation, shouldn't COLOR only receive parameters that have values between 0 and 255?
> 
> You are right, they should be greater than 0, but if they are like this due to math, just ignore use them anyway.

I don't understand, does this mean COLOR can accept any number as a parameter?

**Comment by alexandruradovici** [comment]
Yes
