### ISSUE TITLE
REPEAT with one or more parameters

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#22]
For the _/3_loop/repeat_parameter_error_ test the output should be :
ERROR LINE (line_number): REPEAT has 0 parameters, you wrote (number_of_written_parameters).
But the .out file is empty.

**Comment by HoszuAndreiAlexandru** [comment]
I have a question: in this test file, should the first REPEAT, the one that should output that error, be considered valid for the first loop?

**Comment by alexandruradovici** [comment]
@irina-b-dev is right, repeat should show an error. We fixed it.

The repeat with error is not taken into account. We modified the test as it would yield to a loop inside another loop.
