### ISSUE TITLE
[Devoir 2 - Design Language] Test loop/else.dsn might have an incorrect output

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-ALF/questions#23]
Shouldn't the output for the loop/else.dsn be like [1], meaning that the values for both x1 and y1 are 0 for the LINE element, because the RECTANGLE statement mustn't change the current position of the pen? In the current loop/else.svg file the LINE element takes as values for x1 and y1  the first two parameters of the RECTANGLE statement, meaning that the current pen position is changed by that statement.[2]

[1]

![2021-03-31 (2)](https://user-images.githubusercontent.com/63002082/113061556-e95c0a80-91ba-11eb-9077-765d8c7bc2c2.png)

[2]

![2021-03-31 (3)](https://user-images.githubusercontent.com/63002082/113061615-00026180-91bb-11eb-9183-b3e18159b7b2.png)

**Comment by alexandruradovici** [comment]
You are right, we fixed it.
