### ISSUE TITLE
[Devoir 2 - Design Language] Line polar coordinates possible calculation error

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-ALF/questions#25]
In the simple/line_polar.svg the coordinates for x2 and y2 are: x2 = 448  y2 = 39, but if I calculate manually the coordinates using these formulas:
x = l * cos(a)
y = l * sin(a)

the result for x2 is correct, but the result for y2 should be -39, not 39. Can there be something wrong with the formula used for y in the test file?

**Comment by alexandruradovici** [comment]
In the SVG file, the y axes is increasing downwards. The trigonometric circle has the y axes increasing upwards. This is why the value is inverted.

**Comment by Cristiana959** [comment]
Ah, ok. Thanks.
