### ISSUE TITLE
import problem!!

### ISSUE THREAD

**Issue by yass-11** [UPB-FILS-ALF/questions#26]
please i was working on my homework everything  was goog until the visuel studio made some kind of update and the problem doesn't work anymore and it shows import problem

**Comment by yass-11** [comment]
![2](https://user-images.githubusercontent.com/63538364/113333631-57bfda80-932b-11eb-84ef-bbf80edf2854.PNG)

**Comment by alexandruradovici** [comment]
You are running the typescript source (.ts) with node and that is not possible. Node runs javascript (.js). You have to compile your typescript source first. Take a look at the [first lab](https://ocw.cs.pub.ro/courses/alf/laboratoare/00)
