### ISSUE TITLE
The "else.svg" result is incorrect.

### ISSUE THREAD

**Issue by AbdelmadjidBOUR** [UPB-FILS-ALF/questions#27]
According to the parameters of the rectangle shown in .dsn file  (x1=200  and y1=100) so the top left angle should start at (200, 100) like in the picture number 2.
1/
![image](https://user-images.githubusercontent.com/79580257/113510210-aea6f900-9551-11eb-86d8-c3be8371a92e.png)
2/
![image](https://user-images.githubusercontent.com/79580257/113510218-b8306100-9551-11eb-950e-4f4a72325c1b.png)

**Comment by alexandruradovici** [comment]
Same as #24, the order of points matters for the checker.
