### ISSUE TITLE
[Devoir 3] Cannot find my homework repository

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-ALF/questions#29]
I didn't receive any email with the invitation to collaborate on my homework repository and I can't find the repo anywhere. The same goes for the SDE homework. What can I do in this situation?

**Comment by alexandruradovici** [comment]
It does not seem that you have accepted the homework. Can you post a screenshot of the page that you get when you access the homework link?

**Comment by Cristiana959** [comment]
It simply says page not found.


![2021-04-12 (4)](https://user-images.githubusercontent.com/63002082/114429920-890b9680-9bc6-11eb-9d51-ee44d1be0997.png)

**Comment by alexandruradovici** [comment]
This is when you access the homework link https://classroom.github.com/a/4lETpoEI?

**Comment by Cristiana959** [comment]
Yes it was, but now it worked and redirected me to my assignment repository, thank you! The same thing happens for the SDE homework and I didn't receive any invitation via email for the assignment repo.
