### ISSUE TITLE
Homework 1- Div test incorrect?

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-ALF/questions#3]
For the following test:
push 5.5
push 3.3
stack
div
print

shouldn't the result be 1? [5 div 3]
![Correct output](https://user-images.githubusercontent.com/79825137/111038349-17a6bf80-8431-11eb-9f6c-045a5dc45802.png)

**Comment by alexandruradovici** [comment]
Yes, the CPU uses only integer numbers, rounded to 0 decimals (downwards).

EDIT: yes, it should be 1. Looking into it.

**Comment by alexandruradovici** [comment]
You are right, the division was wrong. We updated the test and uploaded it. Please re-run your tests or just submit another commit.
