### ISSUE TITLE
Differing requirements

### ISSUE THREAD

**Issue by AndreiCristianMoga** [UPB-FILS-ALF/questions#30]
Hi. For ALF Devoir 3, i noticed that the requirements from the ocw.cs.upb.ro are different from the examples provided here on github. Should we write our grammar so it complies with these examples that were linked from github? Or do we follow the directions on the ocw? I am asking this so it's clear which version will count and what we should do
Thank you :)

**Comment by alexandruradovici** [comment]
Please point out an example.

**Comment by AndreiCristianMoga** [comment]
What i found today is that ocw says "array_type array array_name[from:to]" for array definition, github examples use "list:type[from -- to];". At the rest of the differences i thought i saw yesterday, in variable declaration, class (struct), now i just look and see just semantic differences, in which keywords are used, what operators are used, easily adaptable. Sorry if my question was stupid. But, in the end, which will test right between "@ var variable : type <- value ;"(github example) and "declare type name = value"(ocw example)?
Sorry if i wasted your time with this, it seems i did not think through enough at the time. And thank you.

**Comment by DamarisParciu** [comment]
I also found somethig similiar: in the Branches part, the syntax on the site is:
 "if expression 
        ... 
   end;" 
 while on github the exemple is:
 "if n > 2 **then**
	n <- n + 1;
   end;"

**Comment by diana-ghindaoanu** [comment]
The examples have been updated on ocw. Please let me know if there is anything else wrong with the tests.

**Comment by AndreiCristianMoga** [comment]
Sure. I'll close this issue. Thank you very much

**Comment by DamarisParciu** [comment]
> The examples have been updated on ocw. Please let me know if there is anything else wrong with the tests.

Hello! I found one more difference today: on the exemple on ocw, at function call, the function names start with "$", while on GitHub the function name has the properties of a variable.

Which one is the right one?
Thank you!

**Comment by diana-ghindaoanu** [comment]
Hi! The GitHub example is the right one. I also updated on ocw.
