### ISSUE TITLE
[Devoir 3] Errors in test/1_value

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#32]
In the first part of tests I see that when the string has a special character it's not part of the string and it is an error. Shouldn't it be part of the string ?

This happens also at special character

Test for string : 
https://github.com/UPB-FILS-ALF/devoir-3-tests/blob/master/tests/1_value/string_with_special_characters.ast.json

Test for char : 
https://github.com/UPB-FILS-ALF/devoir-3-tests/blob/master/tests/1_value/symbol_with_special_character.ast.json

**Comment by SheepSeb** [comment]
There is also an error at this test:
https://github.com/UPB-FILS-ALF/devoir-3-tests/blob/master/tests/4_function/definition_value.ast.json

**Comment by alexandruradovici** [comment]
This seems to be a bug in the checker, does it work correctly for you? With your grammar, do you get a correct output?

**Comment by SheepSeb** [comment]
I didn't yet implement the errors but this is the output that i get from special char
![image](https://user-images.githubusercontent.com/19248295/115992628-4fc82300-a5d7-11eb-9340-325b3c0926ba.png)
