### ISSUE TITLE
[Devoir 3] Bonus Tests 

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#33]
In the bonus tests there are some lines that I belive to be dependent on the way we wrote the grammer/lexer. For instance if we didn't used the same names in the lexer or if we used fragments to create the tokens it would have another output 

https://github.com/UPB-FILS-ALF/devoir-3-tests/blob/89487e0e0d662dcfe58d03afe254e6325814688c/tests/9_bonus/definition_error.ast.json#L14

**Comment by alexandruradovici** [comment]
We will not check it to be exactly the same.
