### ISSUE TITLE
[Devoir 3] Incorrect test?

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#35]
In the 6_struct/empty test:
![image](https://user-images.githubusercontent.com/79837301/115996685-f8cb4980-a5e8-11eb-8694-3a2091eb08c7.png)

![image](https://user-images.githubusercontent.com/79837301/115996696-07b1fc00-a5e9-11eb-8dfc-c85f284fa104.png)
shouldn't ClassDefinition's line be 4 instead of 2?

**Comment by alexandruradovici** [comment]
The class is defined at line 2 (starting from 0)

Actually no, it should be line 3. @diana-ghindaoanu please check out solution, I think there is a mistake in the line print.

**Comment by HoszuAndreiAlexandru** [comment]
But here it says it should take the value of the end line? Which should be 4
![image](https://user-images.githubusercontent.com/79837301/116006699-0991b480-a615-11eb-861e-56063f93a3f9.png)
