### ISSUE TITLE
[Devoir 3] Autograding issue

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-ALF/questions#37]
All my tests are failing because I get this error, but I write in the correct output file. What can be the problem?

![2021-04-25 (4)](https://user-images.githubusercontent.com/63002082/116001922-bbbe8180-a5ff-11eb-939a-111d211d9573.png)

**Comment by alexandruradovici** [comment]
Are you sure you are writting the correct output file? It os the second parameter that you get.

**Comment by Cristiana959** [comment]
Yes, I checked multiple times and also made a case if the argument is not given as the requirement says.

**Comment by Cristiana959** [comment]
It was a wrong condition that I put at the end of index.ts. Sorry for to disturb you.
