### ISSUE TITLE
[Devoir 3] Line 25 doesn't exist in file 

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-ALF/questions#38]
At the prime function test it says that i have a mismatch for the output[1] , but there is not line 25 in the first place in the test file. Moreover the output file in the test folder doesn't have line 25 [3]

[1]
![image](https://user-images.githubusercontent.com/19248295/116003921-01cc1300-a609-11eb-9189-702074ace286.png)

[2]
![image](https://user-images.githubusercontent.com/19248295/116003932-101a2f00-a609-11eb-93c4-abd311528f49.png)

[3]https://github.com/UPB-FILS-ALF/devoir-3-tests/blob/master/tests/8_script/prime_function.ast.json

**Comment by alexandruradovici** [comment]
We output line 24, you output line 25.
