### ISSUE TITLE
[Devoir3]Checker problem

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#39]
For definition_value_empty_expression.alf test (which has an empty statement ), the checker is evaluating my output correctly.

![function_empty_Screenshot from 2021-04-25 21-38-20](https://user-images.githubusercontent.com/72762129/116005223-b1f04a80-a60e-11eb-89c2-7ca7e6f4a2c7.png)

But for empty_statement.alf it doesn't work.
Here is my output when i run it locally:
![local_empty_Screenshot from 2021-04-25 21-37-11](https://user-images.githubusercontent.com/72762129/116005224-b288e100-a60e-11eb-8640-89f8e5e442be.png)

Here is the output that the checker says i have:
![empty_error_Screenshot from 2021-04-25 21-33-33](https://user-images.githubusercontent.com/72762129/116005225-b288e100-a60e-11eb-886a-7b2d8951173f.png)

(i don't understand why the order of the properties different)

**Comment by alexandruradovici** [comment]
You are missing the id.
