### ISSUE TITLE
Homework 1 - Grading question

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-ALF/questions#4]
On the homework website the grading specifies labels as 10% of the final grade.
But implementing a solution without labels will result in a lower grade than 90% because labels are present in other tests as well.
Is this intentional? Thanks in advance.

**Comment by alexandruradovici** [comment]
Looking into it.

**Comment by alexandruradovici** [comment]
Yes, one register test contains labels, we changed it to line numbers.
