### ISSUE TITLE
[devoir4] [symbol_table] Unknown id "FunctionDeclaration"

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#42]
I don't know how to handle **FunctionDeclaration** nodes.
In the previous homework there wasn't any node with that id. 
I could only find this type of node in [2_message/definition_value](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/2_message/definition_value.alf).
Looking at the alf code, this node looks like a normal **FunctionDeclaration** node. But apparently, in the [ast.json file](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/2_message/definition_value.alf.ast.json) there is no function node in the symbol table. 
If I don't add any function in the symbol table there should be errors in the **ast.json file** because the function parameters aren't declared in the symbol table but used later in an expression. However I cannot find any error objects in the output file either.

**Comment by diana-ghindaoanu** [comment]
It was a mistake, it actually is FunctionDefinition.
It will be fixed today in a checker update.
