### ISSUE TITLE
[Devoir 4] [symbol_table] Missing expression type

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#43]
I have found so far 3 tests that don't seem to have the **type** property defined for some expressions.

- [3_expression/variable.alf.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/3_expression/variable.alf.json)
- [3_expression/variable_and_message.alf.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/3_expression/variable_and_message.alf.json)
- [3_expression/comparison.alf.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/3_expression/comparison.alf.json)

Here is my output for the second test file vs the output from the tests folder.

![image](https://user-images.githubusercontent.com/72762129/119170786-6d6c9900-ba6c-11eb-8c54-eee8f1afa64a.png)

The outuput from the test folder doesnt seem to contain type for   [ n + exec number() ](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/3_expression/variable_and_message.alf)

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
