### ISSUE TITLE
[Devoir4][symbol table] Unclear order of Variable node properties 

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#45]
Symbol and type have different order in the following examples:

3_expression/variable.alf.json
![image](https://user-images.githubusercontent.com/72762129/119177941-b248fd80-ba75-11eb-95e2-9f04a8b1c4aa.png)
4_class/acceess.alf.json
![image](https://user-images.githubusercontent.com/72762129/119177689-59796500-ba75-11eb-8012-141e31124232.png)

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
