### ISSUE TITLE
[Devoir4][symbol-table] Incomplete input ast

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#46]
In [7_bonus/assign_function.alf](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/7_bonus/assign_function.alf) test, the [AST](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/7_bonus/assign_function.alf.ast.json) doesn't contain the names of the function parameters for the **FunctionDefinition** node.

![image](https://user-images.githubusercontent.com/72762129/119185304-4c617380-ba7f-11eb-81f3-e9a1020d97aa.png)

This is a problem because I'm trying to use the variable **n** (which is given as a function parameter) in the for loop.

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
