### ISSUE TITLE
[Devoir 4] missing expression type

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#47]
In the 3_expression/comparison.alf.json file, the main expression's type is missing:
![image](https://user-images.githubusercontent.com/79837301/119219441-4ce52300-baee-11eb-9ec5-59ebaed760ca.png)
Shouldn't there be a "type": "boolean" after the symbol?

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
