### ISSUE TITLE
[Devoir 4] undefined variable in test

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#48]
In the 6_error/not_class_property test, it seems like the Variable node for "t" does not have a title, but a value instead:
![image](https://user-images.githubusercontent.com/79837301/119220994-ccc2bb80-baf5-11eb-828f-5917de17053a.png)
And it does not appear in the output that the variable was not declared, even though the node has been visited and now has a symbol:
![image](https://user-images.githubusercontent.com/79837301/119221071-3b077e00-baf6-11eb-8cbd-9b629f8a8f1b.png)

![image](https://user-images.githubusercontent.com/79837301/119221023-f54ab580-baf5-11eb-96e9-265819006c53.png)

**Comment by diana-ghindaoanu** [comment]
The "value" issue will be fixed today in a checker update. 
The variable "t" is not actually declared. You can see that the first error is NOT_ARRAY, because it is trying to access v as an array, when it actually is a struct.
