### ISSUE TITLE
[Devoir 4] incorrect error

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#49]
In the 6_error/not_class test, the NOT_STRUCT error found contains only the variable type, but on the website it says that it should contain the variable name?
![image](https://user-images.githubusercontent.com/79837301/119221728-50ca7280-baf9-11eb-9267-1cc0f8ab3b43.png)
![image](https://user-images.githubusercontent.com/79837301/119221733-56c05380-baf9-11eb-98a7-7aecf0a749a7.png)

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
