### ISSUE TITLE
[Devoir 4] error property order

### ISSUE THREAD

**Issue by HoszuAndreiAlexandru** [UPB-FILS-ALF/questions#50]
In the 6_error/type_expression_left_right test, in the TYPE_EXPRESSION error the op property appears after the left and right ones:
![image](https://user-images.githubusercontent.com/79837301/119225173-e15d7e80-bb0a-11eb-9e52-2b621e4702b1.png)
but it looks like it should appear before them:
![image](https://user-images.githubusercontent.com/79837301/119225185-ef130400-bb0a-11eb-9017-202b040a8e46.png)

**Comment by diana-ghindaoanu** [comment]
will be fixed today in a checker update
