### ISSUE TITLE
[Devoir4] Missing symbol property for Value nodes and Variable nodes

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-ALF/questions#52]
In most of the tests, the **symbol** property is present for value and variables nodes.
However, for [parameters.alf.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/7_bonus/parameters.alf.json) , [assign_function.alf.ast.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/7_bonus/assign_function.alf.json) and [paremeters_error.alf.ast.json](https://github.com/UPB-FILS-ALF/devoir-4-tests/blob/main/tests/7_bonus/paremeters_error.alf.json) it is missing from most of those nodes.

**Comment by diana-ghindaoanu** [comment]
it will be fixed in an update today
