### ISSUE TITLE
[calculatrice] <test>question

### ISSUE THREAD

**Issue by AhmedJebara** [UPB-FILS-ALF/questions#54]
i have an issue with the tests of the first homework calculator , my code works correctly on pc but nothing works on github , i uploaded the files (calculator.js,package.json,package-lock.json)by drag and drop on my repository on github because i could not do it by commit push from visual studio even i'am meeting some error message to do the link , can you help me with some steps to resolve this issue .
As i understand from the autograding test , it tells me always , module not found and i think must add the node module file to the repository but i can not do that by drag and drop .

**Comment by diana-ghindaoanu** [comment]
First of all, this is a **TypeScript** homework, which means you should create a **.ts** file and your code should be written in TypeScript. Also please name your main file _index.ts_ and update the package.json file accordingly. 
Don't forget to add all the modules your project needs to your package.json file.
