### ISSUE TITLE
[calculatrice]<All tests have failed>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-ALF/questions#55]
I changed the name of the main file to "calculatrice.ts" in package.json
![Screenshot (762)](https://user-images.githubusercontent.com/101173949/159271208-0d057bda-0e56-4610-a74c-100be2e6b9d6.png)
But I still receive this error for all of the tests
![Screenshot (763)](https://user-images.githubusercontent.com/101173949/159271310-b1eab730-e487-465f-9b7a-acce0013a09f.png)

**Comment by alexandruradovici** [comment]
The name of your main file has to be index.ts, as it was in the initial commit of the repository.

The checker is trying to run index.js (the compiled ts file) and it does not find it.
