### ISSUE TITLE
[calculatrice]<Division with float fail>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-ALF/questions#56]
I'm failing the test with the float division. There is a very small difference between my result and the expected result, something like 0.0000002, and I don't know where it comes from.

**Comment by alexandruradovici** [comment]
This might be due to rounding. @diana-ghindaoanu can you take a look at her code and yours?

**Comment by diana-ghindaoanu** [comment]
will do

**Comment by diana-ghindaoanu** [comment]
Indeed, this is a rounding problem. If your code is correct, you will receive the points for this test.
