### ISSUE TITLE
[calculatrice]<sin&cos test bug>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-ALF/questions#57]
The tests for the cos and sin expect the result for a radian value, while the homework's requirements say we have to do the functions for a value in degrees.

**Comment by CAmi307** [comment]
Also, the test for the help command fails if I replace "Author" with my name

**Comment by ioanaculic** [comment]
> 

Please open a different issue with this.

**Comment by diana-ghindaoanu** [comment]
Tests fixed for sin and cos
