### ISSUE TITLE
[calculatrice] <float divide>

### ISSUE THREAD

**Issue by AhmedJebara** [UPB-FILS-ALF/questions#59]
i have an issue in the test , could not submit the value because of the fixed round 
![image](https://user-images.githubusercontent.com/61389261/159544736-1078274b-4707-44af-a22d-068a7690cbe9.png)

**Comment by diana-ghindaoanu** [comment]
I think this is a rounding problem. If your code for this function is correct, you will receive the points for this test.

**Comment by ahmed045** [comment]
and here
![image](https://user-images.githubusercontent.com/61389261/159546227-3ae5da1c-8656-4c8b-8e4e-51bac93b103c.png)

**Comment by ahmed045** [comment]
the same thing here too
![image](https://user-images.githubusercontent.com/61389261/159546534-e30c5543-a690-40e8-a85e-cf7b0edfe8f8.png)

**Comment by diana-ghindaoanu** [comment]
Please open a different issue if it's not related to the floating point issue.
