### ISSUE TITLE
PROBLEM AU NIVEAU D INSTALLATION SDE

### ISSUE THREAD

**Issue by ikarkaoun** [UPB-FILS-ALF/questions#6]
Bonjour
j'ai un probleme au niveau de demarrage de linux j ai suivi tous les instructions mais j arrive pas a resoudre ce petit probleme 
j espere que vous pouvez me donner des instructions a suivre parce que j ai essayé plusieurs methodes mais ce marche pas merci 
![problem](https://user-images.githubusercontent.com/79980237/111288712-1a7dfc00-864d-11eb-8a3e-b592581f69fe.png)

**Comment by alexandruradovici** [comment]
Please take a photo of your BIOS settings with the Virtualization option.

**Comment by ikarkaoun** [comment]
![PROB](https://user-images.githubusercontent.com/79980237/111297021-d3483900-8655-11eb-98e0-46d8b0e33c8e.png)

**Comment by alexandruradovici** [comment]
This is Windows Features, not the BIOS. Please read carefully the chat from the TP2 regarding this topic.
