### ISSUE TITLE
[calculatrice] <Bonus subtract array>

### ISSUE THREAD

**Issue by AhmedJebara** [UPB-FILS-ALF/questions#61]
i could not understand here why it does not work , could you explain ? , because in my code it is working correctly i think
![image](https://user-images.githubusercontent.com/61389261/159561209-9347be2f-d227-4ba0-85f5-35f50424f470.png)
![image](https://user-images.githubusercontent.com/61389261/159561535-a9a4819f-3327-4409-94fb-23e210efbb93.png)

**Comment by diana-ghindaoanu** [comment]
in your code you are verifying if complex mul has exactly 4 parameters. The test that is failing (subtract_array.a) uses more than 4 parameters (2 2 5 -6 5 -7 3 6 7 3 complex -), because you should be able to subtract more than 2 complex numbers.

**Comment by AhmedJebara** [comment]
ah ok , i understand , thank you
