### ISSUE TITLE
[Calculatrice]<Complex add test>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-ALF/questions#62]
In this test the program should consider b2 equal to 0?
![tmp_25617c03-e119-4fd6-8cfc-d6e278240641.jpg](https://user-images.githubusercontent.com/101173949/159787336-957aa268-bd29-4b49-896c-33b74debc57e.jpg)

**Comment by diana-ghindaoanu** [comment]
yes

**Comment by alexandruradovici** [comment]
Yes.

**Comment by CAmi307** [comment]
So technically the only error regarding the number of parameteres occurs when i insert only one complex number, right?

**Comment by diana-ghindaoanu** [comment]
yes, it has the same rule as the classic addition, you need to have at least 2 numbers
