### ISSUE TITLE
[calculatrice] <multiply_array>

### ISSUE THREAD

**Issue by AhmedJebara** [UPB-FILS-ALF/questions#63]
![image](https://user-images.githubusercontent.com/61389261/159794042-892bfdc3-d12d-472c-8119-aa470cb5febd.png)
![image](https://user-images.githubusercontent.com/61389261/159794085-67e8559a-079d-401d-9464-bb3d423749ce.png)
![image](https://user-images.githubusercontent.com/61389261/159794129-ce2c7ce8-5ae1-4432-8133-a8503c6d8f3b.png)

the result for this test should not be 9588+1524i ?

**Comment by AhmedJebara** [comment]
![image](https://user-images.githubusercontent.com/61389261/159800930-9feab781-2540-4c6f-9ed7-b7fd6db327f8.png)

**Comment by diana-ghindaoanu** [comment]
I changed the output for that test, thanks for noticing!
