### ISSUE TITLE
[design]<output file not found>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-ALF/questions#65]
I have a file named output.svg, and i wrote in it the specific command for drawing a line, but i get this error saying i dont have the file
![image](https://user-images.githubusercontent.com/101173949/161396893-16a81185-5bd5-4430-a2e8-994d707e23fb.png)

**Comment by diana-ghindaoanu** [comment]
I think this issue was solved, right? I can't find this problem in your tests anymore.

**Comment by CAmi307** [comment]
Yess. Thank you.
