### ISSUE TITLE
[design] tests

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-ALF/questions#66]
![eroare test](https://user-images.githubusercontent.com/96741919/161428135-a4612a88-49a0-46c1-a7fe-b0288e71522e.PNG)
All my tests get a similar error. I compared my svg file to the svg test file and, besides the comments and spacing, they are identical.

**Comment by diana-ghindaoanu** [comment]
Please make sure that your code is indented

**Comment by alexandruradovici** [comment]
I tested your homework, running for 1_simple/all.dsn outputs

```svg
<?xml version="1.0" encoding="UTF-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1024" height="768">
</svg>
```

This is not correct.

**Comment by alexandruradovici** [comment]
Got the problem. Line endings are '\r\n' in Windows and just '\n' in UNIX systems, which includes Linux. The checker works on Linux. To make it compatible with both, just use a regular expression for `split` where \r is optional.

**Comment by alexandruradovici** [comment]
Lines in the input files may have spaces at the end.

**Comment by TeodoraMiu** [comment]
thank you
