### ISSUE TITLE
 [simulator] Label issue

### ISSUE THREAD

**Issue by DeaconuDavidCatalin** [UPB-FILS-ALF/questions#7]
What should happen in the following scenario:

my command file is:
push 2
jump twow
push 3
push 2
two: push 4
push 5
stack

as you can see, I have the label 'two', but in my jump command I specify a not existing label (twow); what should happen next?

I display an error saying that there is a non-existing label, then I proceed with the next lines?
What happens when I reach to the line with the label? Logically I should not ignore it, should I? (the label is just a shortcut that we can take or not, is it?)

Should I still execute 'push 4' or not? (considering the fact that i reached the line not by jumping, but by parsing the file row by row)

**Comment by alexandruradovici** [comment]
> What should happen in the following scenario:
> 
> my command file is:
> push 2
> jump twow
> push 3
> push 2
> two: push 4
> push 5
> stack
> 
> as you can see, I have the label 'two', but in my jump command I specify a not existing label (twow); what should happen next?
> 
> I display an error saying that there is a non-existing label, then I proceed with the next lines?

If you encounter an error, you display it and ignore that line with the error. All the others are executed. In you example, you will not execute the jump, write the error, and execute push 3 afterwards. 

> What happens when I reach to the line with the label? Logically I should not ignore it, should I? (the label is just a shortcut that we can take or not, is it?)
> 
> Should I still execute 'push 4' or not? (considering the fact that i reached the line not by jumping, but by parsing the file row by row)

When you get to a line with a label, the label is ignored and the instruction is executed. It does not matter if that label is used or not. In your example, push 4 is executed as normal.

**Comment by DeaconuDavidCatalin** [comment]
Thank you !
