### ISSUE TITLE
[semantic] parametrii de intrare cu ast

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-ALF/questions#73]
De ce nu se ia de la linia de comanda ca fisierul de input fisierul de tip .alf, ca sa il parsam direct cu visitor-ul alf obisnuit (la care adaugam semantica)?

**Comment by alexandruradovici** [comment]
Pentru ca nu toti aveti tema 3 facuta complet, deci nu aveti cum sa il parsati toti. Voi primiti acum rezultatul lui visitor, peste care av trebui sa va faceti voi sistemul de parcurgere.

**Comment by TeodoraMiu** [comment]
Deci practic ar trebui sa facem inca o gramatica si inca un visitor pt fisierul json cu ast-ul?

**Comment by alexandruradovici** [comment]
Nu, javascript stie sa faca asta pentru voi.

```js
let data = fs.readFileSync(filename);
let json = JSON.parse(data);
```

Eu as face pentru fiecare clasa din AST o functie `fromJSON` cariea ii dau ca parametru partea de JSON din care trebuie sa creeze clasa. Daca nu vrei asta, poti direct folosi JSON-ul ca obiect far tip, sau, daca esti sigura ca JSON-ul respecta formatul calsei, convertesti bucata respetctiva cu `let node = json.node.... as Node...`
