### ISSUE TITLE
[calculatrice] execution ligne de commande ne fonctionne pas

### ISSUE THREAD

**Issue by PrimexJF** [UPB-FILS-ALF/questions#74]
![image](https://user-images.githubusercontent.com/126392138/228314201-04399661-3723-4250-92df-4ca4c61ac307.png)
Bonjour, il ne marche pas pour moi d'executer le programme par ligne de commande, il ne reconnait pas Cow

**Comment by alexandruradovici** [comment]
Compile the java files using `javac org/example/*.java`and run them using `java -cp . org.example.Main`.
