### ISSUE TITLE
Local ruleaza, in teste nu ruleaza deloc

### ISSUE THREAD

**Issue by LauraNeamtu15** [UPB-FILS-ALF/questions#76]
@CAmi307 
Desi local ruleaza si imi genereaza fisierul de output, in teste primesc urmatoarea eroare 
![image](https://user-images.githubusercontent.com/122366887/235346445-0ae38680-4870-453d-987e-dffb5a85e05b.png)
Oare ce pot face?

**Comment by CAmi307** [comment]
Testele iti pica pentru ca pica testul de build.

Ai generat fisierele AlfParser.java, AlfLexer.java, AlfVisitor.java etc, in mai multe parti ale proiectului. Ele trebuie sa fie la acelasi path cu Main.java. Incearca sa stergi fisierele de la toate path-urile pe care le-ai generat, si vezi ca ai si niste importuri care genereaza erori. Push-uieste inca o data dupa si vezi daca e ok.

Daca vrei sa rulezi local poti fie sa folosesti codespace si sa dai "make" pentru build si apoi sa rulezi testele (clonezi devoir-3-tests in repoul tau si apoi rulezi de la path-ul repo-ului de reste scriptul run.sh pentru fiecare test), fie daca vrei sa folosesti IntelliJ sa compilezi si sa rulezi din command line (javac si java) sau sa dai run din IntelliJ dar sa hardcodezi argumentele (verifica si readme).
