### ISSUE TITLE
[alf] assertion error

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-ALF/questions#77]
Am mutat fisierele generate in acelasi path cu Main.java, dar tot primesc aceasta eroare.
![image](https://user-images.githubusercontent.com/101063308/236398718-8f62920e-4e02-4350-a6a0-2d98a95c7cf1.png)

**Comment by alexandruradovici** [comment]
Iti merge programul, e eroare de output, nu e corect AST-ul, `title` e diferit.
