### ISSUE TITLE
[semantic] erori la teste

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-ALF/questions#78]
Am dat push si mare parte din testele de la partea de variable definition imi dau eroarea aceasta:
![image](https://github.com/UPB-FILS-ALF/questions/assets/101063308/4ed82ff7-c9a7-4d0a-a640-3ad7bdd940eb)
Mentionez ca inainte sa dau push, ca la cealalta tema, am mutat fisierele generate in acelasi folder cu clasa Main

**Comment by alexandruradovici** [comment]
@CAmi307

**Comment by alexandruradovici** [comment]
Problema este la compilare in `Makefile`. Linia de compilare compileaza clasa `Main` si toate dependintele ei. Deoarece inca nu folosesti toate clasele din `type` in `Main`, unele clase, precum `Integer` nu se compileaza. Solutia este sa modifici linia de compilare din `Makefile` astfel incat sa compileze toate clasele.

```
javac -cp "$(CLASSPATH)" -sourcepath ./src/main/java/ -parameters -d out ./src/main/java/org/example/*.java
```

**Comment by CAmi307** [comment]
Am facut update cu corectia comenzii de compilare din Makefile. Poti sa o modifici tu direct sau poti sa iti faci update la repo in functie de template.

Inainte de toate dai push cu modificarile tale, ca in caz ca ceva merge prost sa nu pierzi munca ta. 

Template update:
```

 git remote add template https://github.com/UPB-FILS-ALF/ALF-Devoir3-2023.git
 git fetch template
 git merge template/master --allow-unrelated-histories
```
 
 Dupa asta o sa trebuiasca sa rezolvi conflictele: din tabul de git al lui IntelliJ mergi pe Resolve Conflicts
-pt Makefile dai "Accept Theirs"
-pt orice alt fisier dai "Accept Yours"

Daca ceva a mers prost si vrei sa "cureti" branch-ul si sa revii la modificarile tale :
`git reset --hard origin/master`
