### ISSUE TITLE
[semantic] rezultat gresit la un test

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-ALF/questions#79]
@CAmi307 la testul int_real_symbol, care are programul
![image](https://github.com/UPB-FILS-ALF/questions/assets/101063308/1feb6e83-369b-4f3c-97de-13122215c72b)
Rezultatul corect al testului contine si o undefined_variable_error, desi e doar o expresie
![image](https://github.com/UPB-FILS-ALF/questions/assets/101063308/c1e291f7-fa35-448f-ba98-2a6a0d7670e6)

**Comment by CAmi307** [comment]
Ai dreptate. E gresit. O sa vreificam manual testul acesta, iar daca este corect vom acorda punctajul.
