### ISSUE TITLE
[simulator] <demande explications >

### ISSUE THREAD

**Issue by rania-slimani** [UPB-FILS-ALF/questions#8]
Bonjour monsieur/ madame
Ma question va sembler bête mais mon souci c est que je ne trouve pas comment commencer car je ne comprends pas exactement la demande du devoir je ne trouve pas une question directe Afin de commencer mon devoir 
Serait il possible d’avoir plus d’explications on fait fichier asm ou js ??? Juste quelques explications de plus svp 
Merci

**Comment by alexandruradovici** [comment]
Please read the homework carefully, it has a section that explains the steps that you should take (https://ocw.cs.pub.ro/courses/alf/teme/tema_1#conseils_d_implementation).
