### ISSUE TITLE
[simulateur] comment afficher l'erreur (pour confirmation)

### ISSUE THREAD

**Issue by aldinesr** [UPB-FILS-ALF/questions#80]
Comme je l'ai vu dans les remarques de la documentation, l'erreur doit être exactement telle que vous l'avez écrite. Je veux confirmer par exemple :

"le simulateur tente d'ouvrir un fichier qu'il ne peut pas ouvrir "

ca doit etre:

"unable to open file filename"

ou

"ERROR unable to open file filename.asm(ENOENT: no such file or directory, open filename.asm)"

**Comment by alexandruradovici** [comment]
L'erreur affichée doit être `ERROR unable to open file filename.asm(ENOENT: no such file or directory, open filename.asm)`, où filename est remplacé par le nom de fichier réel
