### ISSUE TITLE
[simulateur] Erreur dans l'exemple de pile

### ISSUE THREAD

**Issue by victorlisman** [UPB-FILS-ALF/questions#81]
La définition de load est qu'elle supprime le premier élément de la pile et le place dans R.
"Elle extrait le premier nombre de la pile et le met dans R (le registre du processeur)"

   ;la pile est [ 1 2 ] 
   load
   ; la pile est [ 1 ]
   ; R est 2

Au lieu de cela, dans l'exemple de sortie, nous avons:

   push 20     ;ajoute 20 à la pile, la pile est [ 20 ]
    push 35     ;ajoute 35 à la pile, la pile est [ 20 35 ] 
    push 9      ;ajoute 9 à la pile, la pile est [ 20 35 9 ]
    stack       ;affiche les contenus de la pile
    load        ;met le sommet de la pile (9 dans notre cas) dans R
    pop         ;supprime le premier nombre de la pile, la pile est [ 20 35 ] et R est [9]
    add         ;ajoute les premiers deux numéros de la pile et met le résultat sur la pile, la pile est [ 55 ] et R est [9]
    print       ;affiche le premier numéro de la pile
    store       ;met la valeur de R sur la pile, la pile est [ 55 9] et R est [9]
    stack       ;affiche la pile

    [ 20 35 9 ]
    55           
    [ 55 9 ] 

Sur la ligne load, 9 est retiré de la pile et placé dans R, puis un pop est effectué et la pile ne restera que 20.

Quelle implémentation pour le chargement est correcte ? Celui où il place le premier élément dans R et le supprime de la pile ou le place simplement dans R ?

**Comment by mihaicostin34** [comment]
L'implémentation correcte de load est celle du tableau, selon laquelle il supprime le premier élément de la pile et le place dans R. L'exemple est faux, nous allons le corriger.

**Comment by alexandruradovici** [comment]
Please translate this in French or English.
