### ISSUE TITLE
[simulateur] Problème de test

### ISSUE THREAD

**Issue by victorlisman** [UPB-FILS-ALF/questions#82]
FR 
La lecture des fichiers en tant qu'argument ne permet pas d'exécuter correctement le programme des tests automatiques :
Il devrait être exécuté à partir de `../devoir-1-tests/tests/$ ` .
Il donne une erreur à chaque test. L'argument passé avec le nom du fichier n'est pas correct.

RO

Ca sa citim fisierele ca argument nu se ruleaza programul la testele automate cum trebuie:
Ar trebui rulat din `../devoir-1-tests/tests/$`  .
Da eroare la fiecare test. Argumentul pasat cu numele fisierului este gresit.

**Comment by mihaicostin34** [comment]
J’ai modifié, maintenant le paramètre passé est le chemin du fichier dans le dossier `devoir-1-tests`.
Par exemple: `devoir-1-tests/tests/register/power.asm`
