### ISSUE TITLE
[simulateur] Problem with the first test

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#84]
The first test seems to always include 
"Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%"
as the beginning output of my program

While all other outputs from subsequent tests do not have this

I reckon this is not from my side

**Comment by mihaicostin34** [comment]
I updated the first test and it now also builds the project, so running it for subsequent tests should no longer give this message
