### ISSUE TITLE
[syntaxique] CompilerFrameworkV2 Problem

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#85]
It seems that some things are broken with the CompilerFrameworkV2 lib (more specifically, the 1.0-SNAPSHOT) that gets shipped with the homework. Up until now I have encountered the next problems:

1. The `SymbolTable` (scope) attached to the `Block` AST Node does not have a `functions` property when being transformed to JSON via the ObjectMapper. I assume this is because `SymbolTable` does not have a `JsonProperty` defined for this.
This is mentioned because the tests provided include this "functions" property for each "scope".<br>
`SymbolTable.class` file provided by IntelliJ:
```java
@com.fasterxml.jackson.annotation.JsonTypeInfo public final class SymbolTable public constructor() {
    @field:com.fasterxml.jackson.annotation.JsonIgnore public final lateinit var owner: domain.interfaces.AstObject /* compiled code */

    @field:com.fasterxml.jackson.annotation.JsonProperty public final var types: kotlin.collections.HashMap<kotlin.String, domain.interfaces.Type> /* = java.util.HashMap<kotlin.String, domain.interfaces.Type> */ /* compiled code */

    @field:com.fasterxml.jackson.annotation.JsonProperty public final var variables: kotlin.collections.HashMap<kotlin.String, kotlin.String> /* = java.util.HashMap<kotlin.String, kotlin.String> */ /* compiled code */
}
```

2. The `VariableDefinition` AST Node seems to not take an `init` AST Node as an argument, the constructor's signature doesn't include it.<br>
`ast/VariableDefinition.class` file provided by IntelliJ:
```java
public final data class VariableDefinition public constructor(variable: domain.ast.Identifier, line: kotlin.Int) : domain.interfaces.Removable, domain.interfaces.IsParent {
    public open var line: kotlin.Int /* compiled code */

    public open var parent: domain.interfaces.IsParent? /* compiled code */

    public open val scope: domain.SymbolTable? /* compiled code */
        public open get

    public final var variable: domain.ast.Identifier /* compiled code */

    // ...
}
```

**Comment by mihaicostin34** [comment]
I have updated the jar inside the homework starter and the issues should be gone. Let me know if the problem persists/anything else comes up.
