### ISSUE TITLE
[syntaxique] JSON Serialization Problem/Test Problem

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#86]
## Problem
I seem to be having trouble with Jackson's ObjectMapper which automatically escapes string values, even when it shouldn't. This is problematic for (at least) the next tests:

- `1_value/string_with_special_characters.alf`
- `1_value/symbol_with_special_character.alf`

## Suggestions
I suggest one of the next 2 things:

1. Change tests to accept the escaped strings
```json
 {
      "@type" : "Value",
      "value" : "this is a string with with special chacaraters \" \\ \n \r ",
      "typeName" : "String",
      "line" : 3
    } 
```
to
```json
 {
      "@type" : "Value",
      "value" : "this is a string with with special chacaraters \\\" \\\\ \\n \\r ",
      "typeName" : "String",
      "line" : 3
    } 
```
2. Change the CompilerFrameworkV2's `domain.ast.Value` to output the `value` variable's value as raw by using the `@JsonRawValue` annotation

I have only tested the latter and had success.

---

If none of these is okay and I should serialize to JSON in another way (configure the `ObjectMapper` or something else) I am open to hearing suggestions!

**Comment by mihaicostin34** [comment]
I have updated the `jar` that comes with the homework starter. Now the `value` field inside the `domain.ast.Value` class has the `@JsonRawValue` annotation and the results should fit the tests without any other modifications.
