### ISSUE TITLE
[syntaxique] IfClause Scoping Problem

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#87]
## Problem

There appears to be a problem with the scoping for the `IfClause` node.

All the tests containing an `IfClause` node have it as follows:

```json
{
  "@type": "IfClause",
  "condition": {"@type":  "BinaryExpression"},
  "then": {"@type":  "Block"},
  "els": {"@type":  "Block"},
  "line": 5,
  "scope": null
}
```

But when instantiating the `domain.ast.IfClause` class, we get the next thing:

```json
{
  "@type": "IfClause",
  "condition": {"@type":  "BinaryExpression"},
  "then": {"@type":  "Block"},
  "els": {"@type":  "Block"},
  "line": 5,
  "scope": {
    "@type" : "SymbolTable",
    "variables" : { },
    "types" : { },
    "functions" : { }
  }
}
```

## What could cause this

This might be because the constructor for `domain.ast.Block` calls `setParentForChildren()` and the `IfClause` has a getter for `scope` to get it from its `parent` or return `null` (since the `IfClause` can only be a child of a `Block` it is safe to assume that its `scope` will never be `null`).

## Suggestions

1. We could modify the tests to have the `scope` of the `IfClause` as a normal `scope`
2. We could modify the `CompilerFrameworkV2` package so that the `scope` getter for `IfClause` returns `null` by default

I've tested the latter and had success.

**Comment by mihaicostin34** [comment]
I could not replicate this on my end. Instantiating the `IfClause` class either manually or using the visitor had the same output as the one in the tests. If the problem persists, let's take a look at it after the next lab. If it is more urgent than that, we can discuss it some other time prior to the lab.

**Comment by popescuatopg** [comment]
We can go over it at the next lab or after it, it's not that urgent.
Thanks!
