### ISSUE TITLE
[syntaxique] Tests With Errors

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#88]
Given that the error message (as well as the type of error - though here I'm not entirely sure if it holds true) has to do with the implementation of the grammar itself, which in our case differs from your implemented grammar, is there a solution (besides hardcoding tests or major grammar modification) to pass the tests/to get points on them?

Example using the file `8_script/prime_function_with_error.json`:

```json
{
  "id" : "Syntax Error",
  "line" : 10,
  "charPosition" : 1,
  "msg" : "extraneous input 'finish' expecting {FUNCTION, 'empty', 'declare', 'exec', 'class', INT, FLOAT, 'string', 'boolean', 'for', 'end', 'repeat', 'while', BOOL_VALUE, 'return', 'if', 'else', '(', '!', INT_NUMBER, FLOAT_NUMBER, VARIABLE, SYMBOL, STRING_TEXT}"
}
```

In comparison with my generated grammar error:

```json
{
  "id" : "Syntax Error",
  "line" : 10,
  "charPosition" : 1,
  "msg" : "extraneous input 'finish' expecting {REDACTED}"
}
```

This is just one example, there are other differences between the type of error and the type of error message that I've encountered.

**Comment by mihaicostin34** [comment]
Indeed, the errors may also depend on the grammar. If you have reached this point, do not make major modifications to your grammar/project. We will take into consideration your results as well as your implementation when grading.
