### ISSUE TITLE
[syntaxique] Tests With Errors

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#89]
The tests that contain errors do not execute correctly, since `verify.js` expects the `.ast.json` file for those to be an object with the `errors` property pointing to an array of errors and as of now their `.ast.json` file is just the array of errors which leads to a deepStrictEqual comparison.

I have created a PR that addresses this problem (https://github.com/UPB-FILS-ALF/devoir-3-tests/pull/5) and would be grateful if you could merge this or give me insight on what I should modify.

**Comment by mihaicostin34** [comment]
I have merged your corrections. Thank you and sorry for the late response.
