### ISSUE TITLE
[simulator] Test files

### ISSUE THREAD

**Issue by DeaconuDavidCatalin** [UPB-FILS-ALF/questions#9]
Hello, 

I would like to be able to run each test manually on my pc (to be able to debug possible problems).

Can I find somewhere the test files(input) and the expected results (output)?

Thank you.

**Comment by alexandruradovici** [comment]
There is a file test.sh in your homework. Running it will clone the tests repository and run the tests. It does not delete the folder with the tests after running them.

**Comment by DeaconuDavidCatalin** [comment]
Thank you !
