### ISSUE TITLE
[syntaxique] No mention of symbol table in instructions - testing stringency 

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-ALF/questions#91]
In the provided output JSON example - we can see that each block contains a scope, which in turns contains a Symbol table, however it isn't mentioned in the instructions what a symbol table is or what it should contain. Please could you clarify?

Also how stringent is the testing for the output JSON - 
Do all of the components have to have the same names, same number of sub-components, exact same structure? 

Thank you so much for your help!

**Comment by mihaicostin34** [comment]
1. Ignore the symbol tables for this homework, as they are out of scope (you can take a look at any test and see that they are empty each time). You will have a dedicated homework related to them.
2. Yes, the structure has to be the same. The order of the fields in a JSON may differ, but the values have to be the same
