### ISSUE TITLE
[syntaxique] If and if-else empty scope

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-ALF/questions#93]
![image](https://github.com/UPB-FILS-ALF/questions/assets/162307601/60b282df-c0d9-4a18-be5d-200dd7dbf980)

Both files in the 5th text expect a null scope for the IfClause structure, however this is not possible. Please can these texts be fixed to reflect a scope similar to the ones in other files?? thank you

**Comment by mihaicostin34** [comment]
See #87 . We have tried replicating this and couldn't. Continue with the rest of the homework and we will take this in consideration when calculating the final points.
