### ISSUE TITLE
[semantique] Broken tests

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-ALF/questions#94]
There seems to be a problem with the tests `array_structure_definition.alf.json` and `array_structure_access.alf.json` from `5_array`, since the `school` struct is defined before being used as a type.
I have created a Pull Request - https://github.com/UPB-FILS-ALF/devoir-4-tests/pull/4 - that should solve these tests, but I would need your help to make sure I haven't missed anything

**Comment by mihaicostin34** [comment]
I have merged the suggested changes. Thank you.
