### ISSUE TITLE
[syntaxique] test failed because of hashmap order?

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-ALF/questions#96]
see attached my output, expected output and test result. It is failing because of the order. I don't believe I have control over that?

Test is  2_message/definition_value.alf

![image](https://github.com/UPB-FILS-ALF/questions/assets/162307601/4fa53822-0e55-4307-a312-f58c9b7de048)
![image](https://github.com/UPB-FILS-ALF/questions/assets/162307601/acf30f80-7cb5-4e90-921d-65832feec67a)
![image](https://github.com/UPB-FILS-ALF/questions/assets/162307601/7fa6a3fb-3fe5-419d-ac52-a910ba124144)

**Comment by mihaicostin34** [comment]
I see that you now pass this test. Does the error persist anywhere else?

**Comment by OmarMDev** [comment]
It seems the test passes when I sync, but fails when testing from within
the codespace.
I will refrain from reporting faulty tests unless they fail after pushing
as well.
