### ISSUE TITLE
[Syntaxique] Semantic error types are not implemented, and wouldm't be possible to return as AstObject

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-ALF/questions#97]
Two very very big issues making it completely impossible to make any form of progress. Note that I have spent HOURS trying to refactor or workaround these very big flaws in the compiler framework, but ultimately it shouldn't even be something I have to deal with at all:

1. The MISSING_RETURN_STATEMENT error type simply does not exist. no matter what, or how we attempt to import it, it is an unresolved reference. 

2. The Analyze() function has to return an AstObject. As per your documentation, even if we were to magically import the non-existant Object, we still wouldn't be able to return it as it doesn't match the required return type of Analyze. 

Please address these issues. Thank you.

**Comment by OmarMDev** [comment]
Since I am being ignored I will hard code the text for the error and I expect not to be penalized. I understand this isn't how we're supposed to do it, but the framework is supposed to work. This has already been a big enough waste of time.

**Comment by alexandruradovici** [comment]
Please do revise your attitude, we are here to help you, you cannot expect us to reply at the minute.

**Comment by OmarMDev** [comment]
Thank you for your reply, 

I apologise if my previous comments came off as disrespectful, certainly not my intention.  Will certainly take this feedback seriously regarding communcation. 

I hope hard coding is ok, as previously inquired? As this, I believe, is a reasonable fix.

**Comment by mihaicostin34** [comment]
I have updated the framework jar delivered with the starter to contain the missing semantic error type, please update your repository.
As for `AstObject`, note that it is an interface (implemented by all classes that represent nodes in the AST), therefor it can be found under `domain.ast.interfaces`
